Project orgflow {
  database_type: 'PostgreSQL'
}

Table requests {
  id uuid [pk]
  request_series_id uuid [not null, note: 'requestのバージョンを束ねるための親番号']
  version_no int [not null, check: `version_no >= 1`, note: '採番はアプリ側で行う']
  status request_status [not null]
  current_applied_approval_route_step_id uuid [null, ref: > applied_approval_route_steps.id]
  applicant_user_id uuid [not null, ref: > users.id]
  organization_id uuid [not null, ref: > organizations.id]
  request_type text [not null,check:
    `request_type IN (
      'transportation_expenses',
      'travel_expenses',
      'equipment_purchase_expenses'
    )`]
  amount int [not null, check: `amount >= 0`, note: "申請金額"]
  created_at timestamptz [not null, default: `now()`]
  indexes {
  	applicant_user_id
  	organization_id
  	(organization_id, status)
    (request_series_id, version_no) [unique]
  }
}