Project orgflow {
  database_type: 'PostgreSQL'
}

Table users {
  id uuid [pk]
  user_name text [not null] // first_name, last_name で別けるべきか？middle_nameがある場合はどうするか？first_name, last_nameの間は半角スペース区切りにする予定だが、半角スペース区切りはアプリ側責務か？数字・記号を入力禁止にする制約はあるのか？フロントエンドとバックエンド側の責務か？
  mail_address text [not null, unique] // メールアドレスの形式("xxx@yyy.zzz")を指定する制約はあるか？フロントエンドとバックエンド側の責務？
  created_at timestamptz [not null, default: `now()`]
}

Table organizations {
  id uuid [pk]
  organization_name text [not null, unique]
}

Table organization_memberships {
  id uuid [pk]
  user_id uuid [not null, ref: > users.id]
  organization_id uuid [not null, ref: > organizations.id]
  indexes {
    (user_id, organization_id) [unique]
  }
}

Table roles {
  id uuid [pk]
  role_name text [not null]
}

Table membership_roles {
  id uuid [pk]
  organization_membership_id uuid [not null, ref: > organization_memberships.id]
  role_id uuid [not null, ref: > roles.id]
  indexes {
    (role_id, organization_membership_id) [unique]
  }
}

Enum request_status {
  in_progress
  approved
  returned
  rejected
  cancelled
}

Table requests {
  id uuid [pk]
  request_series_id uuid [not null, note: 'requestのバージョンを束ねるための親番号']
  version_no int [not null, check: `version_no >= 1`, note: '採番はアプリ側で行う']
  status request_status [not null]
  current_applied_approval_route_step_id uuid [null, ref: > applied_approval_route_steps.id]
  applicant_user_id uuid [not null, ref: > users.id]
  organization_id uuid [not null, ref: > organizations.id]
  request_type text [not null,check:
    `request_type IN (
      'transportation_expenses',
      'travel_expenses',
      'equipment_purchase_expenses'
    )`]
  amount int [not null, check: `amount >= 0`, note: "申請金額"]
  created_at timestamptz [not null, default: `now()`]
  indexes {
  	applicant_user_id
  	organization_id
  	(organization_id, status)
    (request_series_id, version_no) [unique]
  }
}

Enum approval_type {
  approved
  returned
  rejected
}

Table approvals {
  id uuid [pk]
  user_id uuid [not null, ref: > users.id]
  request_id uuid [not null, ref: > requests.id]
  applied_approval_route_step_id uuid [not null, ref: > applied_approval_route_steps.id , Note:"どの承認段に対する承認か"]
  type approval_type [not null, Note:"承認の種類は何か（承認 / 差し戻し / 却下）"]
  approval_message text [null]
  created_at timestamptz [not null]
  indexes {
    (request_id, applied_approval_route_step_id) [unique]
  }
}

Table approval_routes {
  id uuid [pk]
  name varchar(100) [not null]
}

Table approval_route_steps {
  id uuid [pk]
  step_no int [not null]
  approval_route_id uuid [not null, ref: > approval_routes.id]
  indexes {
    (approval_route_id, step_no) [unique]
  }
}

Table approval_route_step_approvers {
  id uuid [pk]
  user_id uuid [not null, ref: > users.id]
  approval_route_step_id uuid [not null, ref: > approval_route_steps.id]
  indexes {
  (user_id, approval_route_step_id) [unique]
  }
}

Table approval_policies {
  id uuid [pk]
  policy_name varchar(100) [not null, unique]
  organization_id uuid [not null, ref: > organizations.id]
  request_type_id uuid [not null, ref: > request_types.id]
  min_amount int [null, Note: "NULLの場合は金額条件なし"]
  approval_route_id uuid [not null, ref: > approval_routes.id]
}

Table request_types {
  id uuid [pk]
  request_type_name varchar(100) [not null, unique]
}

Table applied_approval_routes {
  id uuid [pk]
  request_id uuid [not null, unique, ref: - requests.id]
  approval_policy_id uuid [not null, ref: > approval_policies.id]
}

Table applied_approval_route_steps {
  id uuid [pk]
  step_no int [not null]
  applied_approval_route_id uuid [not null, ref: > applied_approval_routes.id]
  indexes {
    (applied_approval_route_id, step_no) [unique]
  }
}

Table applied_approval_route_step_approvers {
  id uuid [pk]
  user_id uuid [not null, ref: > users.id]
  applied_approval_route_step_id uuid [not null, ref: > applied_approval_route_steps.id]
  indexes {
  (user_id, applied_approval_route_step_id) [unique]
  }
}

Enum operation_type {
  create
  update
  delete
  submit
  approve
  return
  reject
  cancel
  login
  logout
}

Table audit_logs {
  id uuid [pk]
  user_id uuid [not null]
  actor_organization_id uuid [not null]
  target_type varchar(100) [not null, Note: "操作対象名"]
  target_id uuid [not null, Note: "操作対象識別子"]
  operation_type operation_type [not null, Note: "操作種別"]
  occurred_at timestamptz [not null]
}